u8int mlk_scalar_compress_d1(s16int u);
u8int mlk_scalar_compress_d4(s16int u);
s16int mlk_scalar_decompress_d4(u8int u);
u8int mlk_scalar_compress_d5(s16int u);
s16int mlk_scalar_decompress_d5(u8int u);
u16int mlk_scalar_compress_d10(s16int u);
s16int mlk_scalar_decompress_d10(u16int u);
u16int mlk_scalar_compress_d11(s16int u);
s16int mlk_scalar_decompress_d11(u16int u);

void mlk_poly_compress_d4(u8int r[MLKEM_POLYCOMPRESSEDBYTES_D4], const mlk_poly *a);
void mlk_poly_compress_d10(u8int r[MLKEM_POLYCOMPRESSEDBYTES_D10], const mlk_poly *a);
void mlk_poly_decompress_d4(mlk_poly *r, const u8int a[MLKEM_POLYCOMPRESSEDBYTES_D4]);
void mlk_poly_decompress_d10(mlk_poly *r, const u8int a[MLKEM_POLYCOMPRESSEDBYTES_D10]);
void mlk_poly_compress_d5(u8int r[MLKEM_POLYCOMPRESSEDBYTES_D5], const mlk_poly *a);
void mlk_poly_compress_d11(u8int r[MLKEM_POLYCOMPRESSEDBYTES_D11], const mlk_poly *a);
void mlk_poly_decompress_d5(mlk_poly *r, const u8int a[MLKEM_POLYCOMPRESSEDBYTES_D5]);
void mlk_poly_decompress_d11(mlk_poly *r, const u8int a[MLKEM_POLYCOMPRESSEDBYTES_D11]);
void mlk_poly_tobytes(u8int r[MLKEM_POLYBYTES], const mlk_poly *a);
void mlk_poly_frombytes(mlk_poly *r, const u8int a[MLKEM_POLYBYTES]);
void mlk_poly_frommsg(mlk_poly *r, const u8int msg[MLKEM_INDCPA_MSGBYTES]);
void mlk_poly_tomsg(u8int msg[MLKEM_INDCPA_MSGBYTES], const mlk_poly *r);
